version: '3.7'

services:
#    image: foodie-favorites_dotnet:webapp
#    build:
#      context: .
#      env_file:
#        - ./.env
#      dockerfile: ./Dockerfile
#      container_name: asp_net:foodie-favorites
#    #      command: 
#    ports:
#      - 8000:80
#    depends_on:
#      - db


  db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: sql-server_dock
    ports:
      - 1433:1433
    restart: on-failure
    env_file:
      - .env
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}

#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    env_file:
#      - .env
#    environment:
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
#      MYSQL_DATABASE: ${MYSQL_DB}
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    environment:
#      ADMINER_DESIGN: pappu687